run_tests:
  script: 
  # install dependencies
  - npm install

  # build typescript
  - npm run tsc && exit 0
  
  # copy test db
  - cp blank.sqlite mydb.sqlite

  # run sql migrations
  - npm run migrate

  # install mocha
  - npm install -g mocha

  # ready to test!
  - npm test