run_tests:
  script: 

  # print versions
  - node --version
  - npm --version

  # install dependencies
  - npm install

  # build typescript
  - npm run tsc && exit 0
  
  # copy test db
  - cp blank.sqlite mydb.sqlite

  # copy .env file
  - cp .env.example .env

  # run sql migrations
  - npm run migrate

  # ready to test!
  - npm test