run_tests:
  script: 

  # print versions
  - node --version
  - npm --version

  # install dependencies
  - npm install

  - npm run tsc || true

  # build typescript
  - npm run webpack

  - npm run gulp
  
  # copy .env file
  - cp .env.example .env

  # run sql migrations
  - npm run migrate
  - npm run seed

  # ready to test!
  - npm test
