run_tests:
  script: 

  # print versions
  - node --version
  - npm --version

  # install dependencies
  - npm install

  # build typescript
  - npm run tsc && exit 0
  
  # copy test db
  - cp blank.sqlite mydb.sqlite

  # run sql migrations
  - npm run migrate

  # start server
  - npm run server:start

  # ready to test!
  - npm test

  # testing all done :)
  - npm run server:stop
