os: linux
dist: trusty
sudo: true
group: beta

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
  
language: node_js
node_js:
  - "7.5.0"

env:
  global:
    secure: "mxjzojYjbTF1/sCg2E9Iy7AswP9+K0DAyE3imJ87Gm+Law13IzDkV/9zSKp/7YgXcTpUc48pzNO6ofLEDr7/DPfCdL7TO5umJ/Elpr5OCs/uDqA7TJ/TSUCEfcCh+WoOWKK5Wr6mwR1IpXTksX5tDSqc/+Jp6+szp6qgbjDQguQfpYoXBk6/MWzd8MhdtTh642OPhRTkylBpMfcPyieMZNHvtI+PKSIvPcArDVXuTv4VopvGTcadVORRuBkk8YWMR+S69jDrpw6x3TD/WfhAZaPfv2AXZGKTl+8NG3qmT8AxoUUz9vQY9L9UUDBB4Ol13roAYbOWSfZJWrvfh5TSxavJkn8yOD+3M9PpHjLIDgs2iu5CHjecrKF6ac8psH+tRK9TqKZ+Tj+rwhhHkcJ/Yp5/3iJfkDJ4REhbR8YQFUc51DOAUNA/TCvXXKzORIFc8/WmE7LF6hQdE+dnkcNhexYFeC/LUR0V1+9fvmQqZKkZ3lSyf5fGXlCD2adisAmUt8FtwapkIoE4niMH6sbPghLZdYo2GTqyaMNKLDn9pxQJ41chPr+MX/tbxIv4eBio5/JjYZoCEhCGVxC9S6W/IEVUo9wjb2lMbizNcZceEgClrNvZpMwtFSIQZXcuEAajgKqFWKnP9HAaDmUzGOvW6VHs4VgAzdLTC3evsJrP3r0="

script: 

  - sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils

  - rvm get stable 

  - rm -rf .git
  - rm README.md
  - rm .gitignore
  - git init
  - git remote add origin https://github.com/digihum/imperial-entanglements-app.git
  - git pull origin master

  # print versions
  - node --version
  - npm --version

  # install dependencies
  - npm install

  # build typescript
  - npm run compile || true

  # copy .env file
  - cp .env.sqlite .env

  - npm run gulp
  - npm run webpack

  # run sql migrations
  - npm run migrate
  - npm run seed

  # ready to test!
  - npm test

  - npm run dist

after_success: 
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${ACCESS_TOKEN}:x-oauth-basic@github.com" > .git/credentials  
  
  - git config --global user.email "Your email"
  - git config --global user.name "Your Name"
  - git pull origin master
  - git add .
  - git commit -m "Build ${TRAVIS_BUILD_ID}"
  - git push origin master
