os: linux
dist: trusty
sudo: false
group: beta

matrix:
  include:
    - os: osx
      osx_image: xcode7.2
  
language: node_js
node_js:
  - "6.9.1"

env:
  global:
    secure: "bvHVf6PDiY42BUln/KjVbMrNCI24C7MygHg/aPHdio3K6vt7oVGgyjqz2jXpCiwQUwQ61Sd4QOQZZ6oC9aPxbnjmT587zRR9yjoBqNyv9sDVAAEVzKcObrQtX7DMGhANuTmLWImmBKFMJqh9eAlMYq/TqDtRATZGO7PqYCUERVSrvijEDmDLvq2wNavOllEWa2uHD9xXXAuJxNw2Om6hH0Se4LC81Vbyocs+GfjpFO1sMQ7bNO1ODx9T39A/khA+76rDCuZilJy2Mt1RLDrM+TeV/nUDRrUwZns/3XXbOLSeQIIWSF08TvJ6K4Nw0bidCcVwAQN7dhJ01GCKegL2VOfrkUYtVQXKQjzPQyax0AR+Kmzua3q0ujs8unpe0pvbqCMXDXQ77WYmu8vO8Fa/76u1pwJB2g6XY4odRT7AfHgPhxvFK5/eg3I7sWazr/nOszmpPYiOGZk+pZuMBlTdtXoBpQ1QyOFqyivHJO+1ixC0qxbc6ScQ0SAuocNHYjQyGTV+V5E3Z7Io+m+9vaB7tDA/+ePYNELvqFpl092hH/18UZoAVg0btHgy5+00GiAx3k7Cit/S2h52LURlvowpMABB0UHsK6SHc+7MUQYrtITg1ijXmSll2hklBBv2/jMx9R56bfnGpBGe/wGKlSqd3YNwHDEEHyq4eby457Lzpwc="

script: 
  # print versions
  - node --version
  - npm --version

  # install dependencies
  - npm install

  # build typescript
  - npm run tsc || true

  # copy test db
  - cp blank.sqlite mydb.sqlite

  # copy .env file
  - cp .env.example .env

  # run sql migrations
  - npm run migrate
  - npm run seed

  # ready to test!
  - npm test

  - npm run dist

after_success: 
  - rm -rf .git
  - rm README.md
  - rm .gitignore
  
  - git init
  - git config user.name "Tim Hollies"
  - git config user.email "tim.hollies@warwick.ac.uk"

  - git remote add upstream "https://$ACCESS_TOKEN@github.com/digihum/imperial-entanglements-app"
  - git fetch upstream
  - git reset upstream/master

  - touch .

  - git add -A .
  - git commit -m "rebuild at ${rev}"
  - git push -q upstream HEAD:master
