os: linux
dist: trusty
sudo: false
group: beta

matrix:
  include:
    - os: osx
      osx_image: xcode7.2
  
language: node_js
node_js:
  - "6.9.1"

script: 

  - sudo npm uninstall node-gyp -g
  - npm uninstall node-gyp

  # print versions
  - node --version
  - npm --version

  # install dependencies
  - npm install

  # build typescript
  - npm run tsc || true

  # copy test db
  - cp blank.sqlite mydb.sqlite

  # copy .env file
  - cp .env.example .env

  # run sql migrations
  - npm run migrate
  - npm run seed

  # ready to test!
  - npm test

  - npm run dist
