matrix:
  include:
    - os: linux
      dist: trusty
      env:
        - CXX=g++-4.8
      addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.8
    - os: osx
      osx_image: xcode7.2

language: node_js
node_js:
  - "6.9.1"

script: 

  # print versions
  - node --version
  - npm --version

  # install dependencies
  - npm install

  # build typescript
  - npm run tsc && exit 0

  # copy test db
  - cp blank.sqlite mydb.sqlite

  # copy .env file
  - cp .env.example .env

  # run sql migrations
  - npm run migrate
  - npm run seed

  # ready to test!
  - npm test

  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./node_modules/.bin/electron-rebuild; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./node_modules/.bin/build; fi
