os: linux
dist: trusty
sudo: false
group: beta

matrix:
  include:
    - os: osx
      osx_image: xcode7.2
  
language: node_js
node_js:
  - "6.9.1"

script: 

  # print versions
  - node --version
  - npm --version

  # install dependencies
  - npm install

  # build typescript
  - npm run tsc || true

  # copy test db
  - cp blank.sqlite mydb.sqlite

  # copy .env file
  - cp .env.example .env

  # run sql migrations
  - npm run migrate
  - npm run seed

  # ready to test!
  - npm test

  - npm run dist

after_success:
  - rm -rf .git
  - rm README.md
  - rm .gitignore
  - git init
  - git remote add origin https://github.com/digihum/imperial-entanglements-app.git
  - git fetch origin
  - git checkout -b master --track origin/master # origin/master is clone's default
  - git add .
  - git commit -m "Build $($env:TRAVIS_BUILD_ID)"
  - git push origin master
