# Test against this version of Node.js
environment:
  nodejs_version: "6.5.0"
  # Electron's version.
  npm_config_target: "1.4.7"
  # The architecture of Electron, can be ia32 or x64.
  npm_config_arch: x64
  npm_config_target_arch: x64
  # Download headers for Electron.
  npm_config_disturl: https://atom.io/download/electron
  # Tell node-pre-gyp that we are building for Electron.
  npm_config_runtime: electron
  # Tell node-pre-gyp to build module from source code.
  npm_config_build_from_source: true

platform:
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  
  # print versions
  - node --version
  - npm --version

  # install dependencies
  - npm install

  # build typescript
  - npm run tsc || true
  
  # copy test db
  - cp blank.sqlite mydb.sqlite

  # copy .env file
  - cp .env.example .env

  # run sql migrations
  - npm run migrate
  - npm run seed

  - ./node_modules/.bin/build --win

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
