# Test against this version of Node.js
environment:
  nodejs_version: "6.9.1"
  access_token:
    secure: POyM5dzrb6H86XZqJCEp2ky3P3A6vQghzxMwWxP3rZTE1oSaxYbRgBgCVy+bkIso

platform:
  - x64

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  
  # print versions
  - node --version
  - npm --version

  # install dependencies
  - npm install

  # build typescript
  - npm run tsc || true
  
  # copy test db
  - cp blank.sqlite mydb.sqlite

  # copy .env file
  - cp .env.example .env

  # run sql migrations
  - npm run migrate
  - npm run seed

  - npm run dist

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

on_success:
  - rm -rf .git
  - rm README.md
  - rm .gitignore
  - git init
  - git remote add origin https://github.com/digihum/imperial-entanglements-app.git
  - git fetch origin
  - git checkout -b master --track origin/master # origin/master is clone's default
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "Your email"
  - git config --global user.name "Your Name"
  - git add .
  - git commit -m "Build $env:APPVEYOR_BUILD_ID"
  - git push origin master
